// Top Texas cities and counties for permit tracking
export const TEXAS_CITIES = [
  'Houston',
  'San Antonio',
  'Dallas',
  'Austin',
  'Fort Worth',
  'El Paso',
  'Arlington',
  'Corpus Christi',
  'Plano',
  'Laredo',
  'Lubbock',
  'Irving',
  'Garland',
  'Frisco',
  'McKinney',
  'Amarillo',
  'Grand Prairie',
  'Brownsville',
  'Pasadena',
  'Mesquite',
  'Killeen',
  'McAllen',
  'Waco',
  'Carrollton',
  'Denton',
  'Midland',
  'Abilene',
  'Beaumont',
  'Round Rock',
  'The Woodlands',
  'Odessa',
  'Sugar Land',
  'Pearland',
  'College Station',
  'Lewisville',
  'San Angelo',
] as const;

export type TexasCity = typeof TEXAS_CITIES[number];